# Generated by Django 3.0.6 on 2020-05-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destination_desc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc2',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
