# Generated by Django 3.0.6 on 2020-05-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_desc2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='desc2',
        ),
    ]
